#servicios que queremos que corran
services:
  postgres:
    # la imagen de este contenedor será 
    # una base de datos postgres en la versión 18
    image: postgres:18
      # Variables de entorno
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql